In [1]:
#math/data libs
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

#ml libs
import keras
from keras import backend as K
from keras.models import Sequential
from keras. layers import Activation
from keras.layers.core import Dense
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
trainFile = pd.read_csv('./Data/train.csv').drop(columns="datasetId")
testFile = pd.read_csv('./Data/test.csv').drop(columns="datasetId")

trainFile=trainFile.append(testFile)

In [3]:
#train
train_samples = trainFile.drop(columns='condition').to_numpy()
train_labels = trainFile['condition'].to_numpy()

#test
test_samples = testFile.drop(columns='condition').to_numpy()
test_labels = testFile['condition'].to_numpy()

In [14]:
train_samples

array([[0.43597106, 0.29623337, 0.21209913, ..., 0.03539462, 0.94718154,
        0.39574294],
       [0.50603588, 0.37951539, 0.100855  , ..., 0.00679268, 0.96648135,
        0.15501473],
       [0.45279178, 0.34310938, 0.10678409, ..., 0.02431647, 0.94473507,
        0.43494914],
       ...,
       [0.18321341, 0.12845198, 0.19875276, ..., 0.26215531, 0.91287873,
        0.55276817],
       [0.27621512, 0.21461972, 0.06258002, ..., 0.17184441, 0.97585794,
        0.61289951],
       [0.4138708 , 0.31321216, 0.06352917, ..., 0.03284519, 0.94905719,
        0.33210205]])

In [4]:
#normalizing features
scaler = MinMaxScaler(feature_range=(0,1))
train_samples = scaler.fit_transform(train_samples)
test_samples = scaler.fit_transform(test_samples)

#one-hot-encoding labels
one_hot_encoder = OneHotEncoder(categories='auto')
train_labels = one_hot_encoder.fit_transform(train_labels.reshape(-1, 1)).toarray()
test_labels = one_hot_encoder.fit_transform(test_labels.reshape(-1, 1)).toarray()

In [5]:
#build the model
model = Sequential([
    Dense(34, input_shape=[34,], activation='relu'),
#     Dense(20, activation='relu'),
    Dense(10, activation='relu'),
    Dense(2, activation='softmax')
])

In [6]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 34)                1190      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                350       
_________________________________________________________________
dense_3 (Dense)              (None, 2)                 22        
Total params: 1,562
Trainable params: 1,562
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.compile(Adam(lr=.0001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [9]:
#model.fit(train_samples, train_labels, validation_split=0.1, batch_size=10, epochs=3, shuffle=True, verbose=2)
model.fit(train_samples, train_labels, batch_size=10, epochs=10, shuffle=True, verbose=2)

Epoch 1/10
 - 25s - loss: 0.2384 - accuracy: 0.9033
Epoch 2/10
 - 25s - loss: 0.2140 - accuracy: 0.9161
Epoch 3/10
 - 25s - loss: 0.1928 - accuracy: 0.9278
Epoch 4/10
 - 25s - loss: 0.1749 - accuracy: 0.9355
Epoch 5/10
 - 25s - loss: 0.1588 - accuracy: 0.9422
Epoch 6/10
 - 26s - loss: 0.1444 - accuracy: 0.9490
Epoch 7/10
 - 26s - loss: 0.1319 - accuracy: 0.9544
Epoch 8/10
 - 25s - loss: 0.1213 - accuracy: 0.9587
Epoch 9/10
 - 26s - loss: 0.1119 - accuracy: 0.9621
Epoch 10/10
 - 26s - loss: 0.1038 - accuracy: 0.9647


In [15]:
model.save('model.h5')

In [18]:
y_pred=model.predict(test_samples)
y_pred =(y_pred>0.5)

In [21]:
y_pred

array([[ True, False],
       [False,  True],
       [ True, False],
       ...,
       [False,  True],
       [False,  True],
       [False,  True]])

In [22]:
test_labels

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])

In [17]:
test_samples

array([[0.22531332, 0.18486409, 0.08844309, ..., 0.26053516, 0.92367922,
        0.64162155],
       [0.38244367, 0.28799639, 0.0581626 , ..., 0.04047566, 0.99034621,
        0.66112158],
       [0.53098161, 0.39563865, 0.19693847, ..., 0.0183135 , 0.99026903,
        0.33885214],
       ...,
       [0.18331272, 0.12845198, 0.19874266, ..., 0.27243779, 0.91292724,
        0.55324208],
       [0.27636484, 0.21461972, 0.062443  , ..., 0.17858342, 0.97595153,
        0.61357042],
       [0.41409514, 0.31321216, 0.06339303, ..., 0.03413039, 0.9491316 ,
        0.33185303]])

In [23]:
one_hot_encoder

OneHotEncoder(categorical_features=None, categories='auto', drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [28]:
test_labels

array(['nostress', 'stress', 'nostress', ..., 'nostress', 'nostress',
       'stress'], dtype=object)

In [10]:
import numpy as np

import pandas as pd
from sklearn import datasets, svm, metrics
import matplotlib.pyplot as plt

In [ ]:
# trainFile = pd.read_csv('./Data/train.csv').drop(columns="datasetId")
# testFile = pd.read_csv('./Data/test.csv').drop(columns="datasetId")

In [11]:
#features
X_train = trainFile.drop(columns='condition')
y_train = trainFile['condition']
X_test = testFile.drop(columns='condition')
y_test = testFile['condition']

In [18]:
X_train

MEAN_RR    MEDIAN_RR        SDRR      RMSSD       SDSD  SDRR_RMSSD  \
0       885.157845   853.763730  140.972741  15.554505  15.553371    9.063146   
1       939.425371   948.357865   81.317742  12.964439  12.964195    6.272369   
2       898.186047   907.006860   84.497236  16.305279  16.305274    5.182201   
3       881.757864   893.460030   90.370537  15.720468  15.720068    5.748591   
4       809.625331   811.184865   62.766242  19.213819  19.213657    3.266724   
5       923.283866   617.794160  517.536544   9.965976   9.933933   51.930344   
6       973.252908   964.650020   82.405179  10.644196  10.643638    7.741794   
7       715.914682   679.499395  131.477151   9.477727   9.477717   13.872224   
8       814.257021   827.522830   87.014459  14.632232  14.631275    5.946766   
9       959.694591   957.895600   54.904529  12.015400  12.015343    4.569513   
10      848.620915   851.573130   57.886336  14.142654  14.142548    4.093032   
11      933.585605   893.898605  130.081903  16.357782  16.356546    7.952295   
12      708.887292   699.626930  114.018396  11.987998  11.987924    9.511045   
13      772.746607   775.004770   51.610211  10.288162  10.288091    5.016466   
14      810.747807   813.957410   60.471091  19.303488  19.303475    3.132651   
15      627.786933   618.868080  121.417838  17.437636  17.437630    6.962976   
16      925.698847   937.190295  147.670290  14.756286  14.756282   10.007281   
17      761.922715   777.496885  108.347376  17.746108  17.745714    6.105416   
18      776.400178   775.153655   50.205780  10.974996  10.974862    4.574560   
19      810.544431   822.265700   82.669234  14.033955  14.033952    5.890659   
20      801.001194   786.004130  107.714621   8.846026   8.845955   12.176611   
21      811.107635   799.783605  101.252818   8.427791   8.427728   12.014159   
22      793.612042   720.747110  199.962162  14.786004  14.779379   13.523746   
23      994.559909  1006.961650  107.655379  21.844254  21.844196    4.928316   
24      775.171469   787.865115   90.135848  13.426669  13.426301    6.713195   
25      729.501501   722.510640   80.947009  23.538452  23.538266    3.438927   
26      864.213261   865.003415   92.354569  21.997544  21.997299    4.198404   
27      922.092732   948.665510  108.443798  11.461559  11.459967    9.461523   
28      571.660168   567.469775   46.254947   8.850101   8.850075    5.226488   
29      863.244837   859.209900   70.400955  15.123932  15.123932    4.654937   
...            ...          ...         ...        ...        ...         ...   
41003  1028.047924   832.571965  344.110371  13.544936  13.536111   25.405094   
41004   799.968333   800.912535   70.075692  15.950657  15.950641    4.393279   
41005   733.431435   725.478560  133.800400  16.624135  16.623990    8.048563   
41006   968.248212   958.027150  132.181506  14.511963  14.511601    9.108451   
41007   752.380093   754.183760   57.723136   9.563902   9.563671    6.035521   
41008  1025.149479  1023.594650  149.115627  16.045542  16.043520    9.293275   
41009   810.833219   810.734680   54.012156  14.460142  14.459764    3.735244   
41010   738.975658   719.649645  106.543373  13.685881  13.685881    7.784912   
41011   896.601125   881.901210  104.823280  14.550310  14.550304    7.204196   
41012  1093.757520  1091.790200   72.653081  11.682852  11.681682    6.218779   
41013   955.290842   949.173750  119.318824  15.400150  15.399618    7.747900   
41014   721.009541   715.242470   68.750935  22.315299  22.315299    3.080888   
41015   730.058717   749.985530  127.517551  14.378919  14.378462    8.868368   
41016   958.291552   953.075005   77.245425  10.625533  10.625487    7.269793   
41017   785.907404   786.653530   46.296949  12.697805  12.697732    3.646059   
41018   782.589049   688.175200  266.583643  15.904574  15.892520   16.761445   
41019   894.620877   922.758730  128.043541  18.273404  18.273115    7.007098   
41020   785.174994   793.941120   96.08675

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
print('Accuracy of K-NN classifier on training set: {:.2f}'
     .format(knn.score(X_train, y_train)))
print('Accuracy of K-NN classifier on test set: {:.2f}'
     .format(knn.score(X_test, y_test)))

Accuracy of K-NN classifier on training set: 1.00
Accuracy of K-NN classifier on test set: 1.00


In [ ]:
i=0
knn.predict([X_test.iloc[i]])

In [13]:
import pickle

filename = 'knnecg.sav'
pickle.dump(knn, open(filename, 'wb'))

filename = 'annecg.sav'
pickle.dump(model, open(filename, 'wb'))

In [19]:
X_train.dtypes

MEAN_RR              float64
MEDIAN_RR            float64
SDRR                 float64
RMSSD                float64
SDSD                 float64
SDRR_RMSSD           float64
HR                   float64
pNN25                float64
pNN50                float64
SD1                  float64
SD2                  float64
KURT                 float64
SKEW                 float64
MEAN_REL_RR          float64
MEDIAN_REL_RR        float64
SDRR_REL_RR          float64
RMSSD_REL_RR         float64
SDSD_REL_RR          float64
SDRR_RMSSD_REL_RR    float64
KURT_REL_RR          float64
SKEW_REL_RR          float64
VLF                  float64
VLF_PCT              float64
LF                   float64
LF_PCT               float64
LF_NU                float64
HF                   float64
HF_PCT               float64
HF_NU                float64
TP                   float64
LF_HF                float64
HF_LF                float64
sampen               float64
higuci               float64
dtype: object

In [20]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier

clf1 = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf1 = clf1.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf1.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[22158,     0],
       [    0, 18875]])

In [23]:
filename = 'decisiontreeecg.sav'
pickle.dump(clf1, open(filename, 'wb'))

In [26]:
loaded_model = pickle.load(open('decisiontreeecg.sav', 'rb'))
y_pred1 = loaded_model.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred1)
cm

array([[22158,     0],
       [    0, 18875]])